// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oepptoxmwhldytxydiav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lcHB0b3htd2hsZHl0eHlkaWF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNTkxNDksImV4cCI6MjA2MzczNTE0OX0.JOauDDw6xDdpr9lFSAduW9-hkzYVscPmWlYaN-uAePA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);